// <autogenerated>
//   This file was generated by T4 code generator ModelCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;


using Infrastructure.Core.Data;
using Infrastructure.Web.Domain.Entity;
using Infrastructure.Core.Tasks;


namespace Infrastructure.Web.Domain.Configuration
{


    public partial class LogsConfiguration : EntityConfigurationBase<LogsModel, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public LogsConfiguration()
        {
            LogsConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void LogsConfigurationAppend();

        partial void LogsConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

    public partial class ReleaseNoteConfiguration : EntityConfigurationBase<ReleaseNote, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public ReleaseNoteConfiguration()
        {
            ConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigurationAppend();

        partial void ConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }


    public partial class ScheduleTaskConfiguration : EntityConfigurationBase<ScheduleTask, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public ScheduleTaskConfiguration()
        {
            ScheduleTaskConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ScheduleTaskConfigurationAppend();

        partial void ScheduleTaskConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
    //public partial class SearchKeywordsConfiguration : EntityConfigurationBase<SearchKeywords, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public SearchKeywordsConfiguration()
    //    {
    //        SearchKeywordsConfigurationAppend();
    //    }

    //    /// <summary>
    //    /// 额外的数据映射
    //    /// </summary>
    //    partial void SearchKeywordsConfigurationAppend();

    //    partial void SearchKeywordsConfigurationAppend()
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}


    public partial class SysConfigConfiguration : EntityConfigurationBase<SysConfigModel, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysConfigConfiguration()
        {
            SysConfigConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SysConfigConfigurationAppend();

        partial void SysConfigConfigurationAppend() 
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

 

    //    /// <summary>
    //    /// 额外的数据映射
    //    /// </summary>
    //    partial void WechatUserConfigurationAppend();

    //    partial void WechatUserConfigurationAppend() 
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}

   
    //public partial class ArticleImagesConfiguration : EntityConfigurationBase<ArticleImages, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public ArticleImagesConfiguration()
    //    {
    //        SysWechatConfigConfigurationAppend();
    //    }

    //    /// <summary>
    //    /// 额外的数据映射
    //    /// </summary>
    //    partial void SysWechatConfigConfigurationAppend();

    //    partial void SysWechatConfigConfigurationAppend()
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}
}
