// <autogenerated>
//   This file was generated by T4 code generator ModelCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;


using Infrastructure.Core.Data;
using Infrastructure.Web.Domain.Entity;


namespace Infrastructure.Web.Domain.Configuration
{
    /// <summary>
    /// 实体类-数据表映射——Role
    /// </summary> 
    public partial class SysWechatConfigConfiguration : EntityConfigurationBase<SysWechatConfig, Int32>
    { 
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SysWechatConfigConfiguration()
        {
            ConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigurationAppend();

        partial void ConfigurationAppend()
        {
           // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
}
