// <autogenerated>
//   This file was generated by T4 code generator ModelCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>
using System;
using Infrastructure.Core.Data;
using DLYB.CA.Entity;


namespace DLYB.CA.Service.ModelConfigurations.Identity
{
     //<summary>
     //实体类-数据表映射——Role
     //</summary> 
    public partial class ThumbsUpConfiguration : EntityConfigurationBase<ThumbsUp, Int32>
    { 
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public ThumbsUpConfiguration()
        {
            ThumbsUpConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ThumbsUpConfigurationAppend();

        partial void ThumbsUpConfigurationAppend()
        {
           // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
    //public partial class QuestionManageConfiguration : EntityConfigurationBase<QuestionManage, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public QuestionManageConfiguration()
    //    {
    //        ConfigConfigurationAppend();
    //    }
    //    partial void ConfigConfigurationAppend();

    //    partial void ConfigConfigurationAppend()
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}
    //public partial class QuestionImagesConfiguration : EntityConfigurationBase<QuestionImages, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public QuestionImagesConfiguration()
    //    {
    //        ConfigConfigurationAppend();
    //    }
    //    partial void ConfigConfigurationAppend();

    //    partial void ConfigConfigurationAppend()
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}
    //public partial class LogsConfiguration : EntityConfigurationBase<Logs, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public LogsConfiguration()
    //    {
    //        LogsConfigurationAppend();
    //    }

    //    /// <summary>
    //    /// 额外的数据映射
    //    /// </summary>
    //    partial void LogsConfigurationAppend();

    //    partial void LogsConfigurationAppend() 
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}
    ////public partial class SearchKeywordsConfiguration : EntityConfigurationBase<SearchKeywords, Int32>
    ////{
    ////    /// <summary>
    ////    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    ////    /// </summary>
    ////    public SearchKeywordsConfiguration()
    ////    {
    ////        SearchKeywordsConfigurationAppend();
    ////    }

    ////    /// <summary>
    ////    /// 额外的数据映射
    ////    /// </summary>
    ////    partial void SearchKeywordsConfigurationAppend();

    ////    partial void SearchKeywordsConfigurationAppend()
    ////    {
    ////        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    ////    }
    ////}
    //public partial class SysConfigConfiguration : EntityConfigurationBase<SysConfig, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public SysConfigConfiguration()
    //    {
    //        SysConfigConfigurationAppend();
    //    }

    //    /// <summary>
    //    /// 额外的数据映射
    //    /// </summary>
    //    partial void SysConfigConfigurationAppend();

    //    partial void SysConfigConfigurationAppend() 
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}
    public partial class WechatUserConfiguration : EntityConfigurationBase<WechatUser, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public WechatUserConfiguration()
        {
            WechatUserConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void WechatUserConfigurationAppend();

        partial void WechatUserConfigurationAppend() 
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

    public partial class MessageConfiguration : EntityConfigurationBase<Message, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public MessageConfiguration()
        {
            MessageConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void MessageConfigurationAppend();

        partial void MessageConfigurationAppend() 
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

    //public partial class ToolsConfiguration : EntityConfigurationBase<Tools, Int32>
    //{
    //    /// <summary>
    //    /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
    //    /// </summary>
    //    public ToolsConfiguration()
    //    {
    //        MessageConfigurationAppend();
    //    }

    //    /// <summary>
    //    /// 额外的数据映射
    //    /// </summary>
    //    partial void MessageConfigurationAppend();

    //    partial void MessageConfigurationAppend()
    //    {
    //        // HasRequired(m => m.Organization).WithMany(n => n.Roles);
    //    }
    //}

    public partial class ArticleImagesConfiguration : EntityConfigurationBase<ArticleImages, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public ArticleImagesConfiguration()
        {
            ConfigConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigConfigurationAppend();

        partial void ConfigConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

    public partial class ImageInfoConfiguration : EntityConfigurationBase<ImageInfo, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public ImageInfoConfiguration()
        {
            ConfigConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigConfigurationAppend();

        partial void ConfigConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

    public partial class UserBehaviorConfiguration : EntityConfigurationBase<UserBehavior, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public UserBehaviorConfiguration()
        {
            ConfigConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigConfigurationAppend();

        partial void ConfigConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
    public partial class FaqInfoConfiguration : EntityConfigurationBase<FaqInfo, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public FaqInfoConfiguration()
        {
            ConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigurationAppend();

        partial void ConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }

    public partial class SearchKeywordConfiguration : EntityConfigurationBase<SearchKeyword, Int32>
    {
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SearchKeywordConfiguration()
        {
            ConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void ConfigurationAppend();

        partial void ConfigurationAppend()
        {
            // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
}
