// <autogenerated>
//   This file was generated by T4 code generator ModelCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


using System;


using Infrastructure.Core.Data;
using Innocellence.CA.Entity;


namespace Innocellence.CA.Service.ModelConfigurations.Identity
{
    /// <summary>
    /// 实体类-数据表映射——Role
    /// </summary> 
    public partial class SurveyConfiguration : EntityConfigurationBase<Survey, Int32>
    { 
        /// <summary>
        /// 初始化一个<see cref="RoleConfiguration"/>类型的新实例
        /// </summary>
        public SurveyConfiguration()
        {
            SurveyConfigurationAppend();
        }

        /// <summary>
        /// 额外的数据映射
        /// </summary>
        partial void SurveyConfigurationAppend();

        partial void SurveyConfigurationAppend()
        {
           // HasRequired(m => m.Organization).WithMany(n => n.Roles);
        }
    }
}
